version: 2
jobs:
  build:
    docker:
      - image: debian:stretch-slim
    steps:
      - checkout
      - run: echo 'hello'
  test:
    docker:
      - image: debian:stretch-slim
    steps:
      - checkout
      - run: echo 'hello'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
